<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Gym Report {{ $year }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #0070FF;
            padding-bottom: 10px;
        }
        h1 {
            color: #0070FF;
            margin: 0;
        }
        h2 {
            margin: 5px 0;
        }
        .stats {
            margin-bottom: 30px;
        }
        .stat-box {
            border: 1px solid #ddd;
            padding: 10px;
            margin-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .text-right {
            text-align: right;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 10px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
    </style>
</head>
<body>

<div class="header">
    <h1>Gym Management System</h1>
    <h2>Annual Report - {{ $year }}</h2>
    <p>Generated: {{ $generatedAt }}</p>
</div>

<div class="stats">
    <div class="stat-box">
        <strong>Total Revenue:</strong> ₱{{ number_format($totalRevenue, 2) }}
    </div>
    <div class="stat-box">
        <strong>New Members:</strong> {{ $newMembers }}
    </div>
</div>

<h3>Monthly Revenue</h3>
<table>
    <thead>
        <tr>
            <th>Month</th>
            <th class="text-right">Revenue</th>
        </tr>
    </thead>
    <tbody>
        @foreach($monthlyRevenue as $month => $revenue)
        <tr>
            <td>{{ $month }} {{ $year }}</td>
            <td class="text-right">₱{{ number_format($revenue, 2) }}</td>
        </tr>
        @endforeach
        <tr style="font-weight: bold; background-color: #f2f2f2;">
            <td>Total</td>
            <td class="text-right">₱{{ number_format($totalRevenue, 2) }}</td>
        </tr>
    </tbody>
</table>

<div class="footer">
    <p>This report is automatically generated by the Gym Management System.</p>
</div>

</body>
</html>